---
- hosts: all
  vars:
    docker_image: "{{ docker_image }}"
  tasks:
    - name: Run docker container
      docker_container:
        name: my_app
        image: "{{ docker_image }}"
        ports:
          - "80:5000"
        restart_policy: always

